version: '2'
networks:
  network-2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/24
        gateway: 172.21.0.1

services:
  app:
    build:
      context: .
    volumes:
     - "./app:/opt/app"
    networks:
      network-2:
        ipv4_address: 172.21.0.2
    ports:
     - "80:8090"
#    ports:
#      - "80:80"	 