#!/bin/sh -e
#
# script for starting/stopping the HornetQ standalone server
#
### BEGIN INIT INFO
# Provides:          hornetq
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

USER=hornetq
GROUP=hornetq
NAME=hornetq
HORNETQ_HOME=/opt/jboss/hornetq-2.4.0.Final
DAEMON_PATH=$HORNETQ_HOME/bin/
chown -R $USER:$GROUP $HORNETQ_HOME
cd $HORNETQ_HOME
PID=$NAME
PIDFILE=/var/run/$NAME.pid

if [ `id -u` -ne 0 ]; then
        echo "You need root privileges to run this script"
        exit 1
fi

case "$1" in
	start)
	    printf "%-50s" "Starting $NAME..."
            echo $PID > $PIDFILE
	    printf "%s\n" "Ok"
	    cd $DAEMON_PATH
            sudo -g $GROUP -u $USER ./run.sh
	;;
	status)
            printf "%-50s" "Checking $NAME..."
	    if [ -f $PIDFILE ]; then
	        echo "Running"
	    else
	        printf "%s\n" "Service not running"
	    fi
        ;;
	stop)
	    printf "%-50s" "Stopping $NAME"
       	    cd $DAEMON_PATH
	    if [ -f $PIDFILE ]; then
	        sudo -g $GROUP -u $USER ./stop.sh
	        printf "%s\n" "Ok"
	        rm -f $PIDFILE
	    else
	        printf "%s\n" "pidfile not found"
	    fi
	;;
        restart)
	    $0 stop
	    $0 start
	;;

	*)
	    echo "Usage: $0 {status|start|stop|restart}"
	    exit 1
esac

